blank_issues_enabled: false
contact_links:
  - name: 📚 Documentação do Sistema
    url: https://github.com/jaisonschmidt/java-copilot-code-agent4/blob/main/docs/README.md
    about: Consulte a documentação completa do sistema antes de abrir uma issue
  - name: 💬 Dúvidas Gerais
    url: https://github.com/jaisonschmidt/java-copilot-code-agent4/discussions
    about: Para dúvidas gerais, use as Discussões do GitHub
