---
name: 🎨 Melhorias de Interface (UI/UX)
description: Sugerir melhorias na interface do usuário ou experiência
title: "[UI/UX]: "
labels: ["enhancement", "ui-ux", "frontend", "copilot-assignable"]
assignees: []
body:
  - type: markdown
    attributes:
      value: |
        ## 🎨 Solicitação de Melhoria de Interface
        Use este formulário para sugerir melhorias na aparência ou usabilidade do sistema.
        
  - type: dropdown
    id: improvement-type
    attributes:
      label: Tipo de Melhoria *
      description: Que tipo de melhoria você está sugerindo?
      options:
        - Visual/Estética - Cores, fontes, espaçamento
        - Usabilidade - Facilidade de uso, navegação
        - Acessibilidade - Melhorias para todos os usuários
        - Responsividade - Adaptação a diferentes telas
        - Performance - Velocidade de carregamento/interação
        - Feedback Visual - Indicadores de estado, mensagens
        - Outro
    validations:
      required: true

  - type: dropdown
    id: affected-page
    attributes:
      label: Página/Componente Afetado *
      description: Onde esta melhoria deve ser aplicada?
      options:
        - Página Principal (listagem de atividades)
        - Cards de Atividades
        - Modal de Login
        - Modal de Inscrição
        - Filtros de Busca
        - Cabeçalho/Header
        - Mensagens de Feedback
        - Responsividade Mobile
        - Todo o sistema (tema geral)
        - Outro
    validations:
      required: true

  - type: textarea
    id: current-state
    attributes:
      label: Estado Atual *
      description: Como está atualmente?
      placeholder: "Ex: Os filtros estão em uma sidebar, mas em mobile ficam muito comprimidos..."
    validations:
      required: true

  - type: textarea
    id: proposed-improvement
    attributes:
      label: Melhoria Proposta *
      description: O que você sugere mudar?
      placeholder: "Ex: Em mobile, os filtros deveriam ser um modal colapsável com um botão 'Filtros'..."
    validations:
      required: true

  - type: textarea
    id: why-improvement
    attributes:
      label: Por que esta Melhoria? *
      description: Que problema ou dificuldade atual isso resolve?
      placeholder: "Ex: Professores reclamam que é difícil usar o sistema no celular para fazer inscrições rápidas..."
    validations:
      required: true

  - type: dropdown
    id: user-impact
    attributes:
      label: Impacto no Usuário *
      description: Quantos usuários serão beneficiados?
      options:
        - Todos os usuários
        - Maioria dos usuários
        - Alguns usuários (casos específicos)
        - Principalmente mobile
        - Principalmente desktop
    validations:
      required: true

  - type: textarea
    id: color-scheme
    attributes:
      label: Esquema de Cores
      description: Se for mudança visual, especifique cores (hex codes se possível)
      placeholder: "Ex: Mudar botão de #1a237e para #2196f3 para melhor contraste..."

  - type: textarea
    id: layout-changes
    attributes:
      label: Mudanças de Layout
      description: Descreva mudanças estruturais no layout
      placeholder: "Ex: Mover botão de login do canto superior direito para o centro do header..."

  - type: checkboxes
    id: accessibility-features
    attributes:
      label: Recursos de Acessibilidade
      description: Sua sugestão inclui melhorias de acessibilidade?
      options:
        - label: Contraste de cores adequado (WCAG)
        - label: Navegação por teclado
        - label: Leitores de tela (ARIA labels)
        - label: Tamanhos de fonte ajustáveis
        - label: Ícones com texto alternativo
        - label: Não aplicável

  - type: textarea
    id: responsive-behavior
    attributes:
      label: Comportamento Responsivo
      description: Como deve se comportar em diferentes tamanhos de tela?
      placeholder: |
        - Desktop (>1200px): Layout em três colunas
        - Tablet (768-1199px): Layout em duas colunas
        - Mobile (<768px): Layout em uma coluna, menu colapsável

  - type: textarea
    id: examples-inspiration
    attributes:
      label: Exemplos ou Inspiração
      description: Links ou imagens de exemplos similares em outros sites
      placeholder: "Ex: Similar ao Material Design de Google para cards: https://..."

  - type: textarea
    id: mockup
    attributes:
      label: Mockup ou Screenshot
      description: Se possível, adicione mockup, wireframe ou screenshot anotado
      placeholder: "Cole imagens ou links aqui..."

  - type: checkboxes
    id: css-changes
    attributes:
      label: Escopo de Mudanças CSS
      description: Que tipo de mudanças CSS serão necessárias?
      options:
        - label: Mudanças mínimas (ajustes de estilo)
        - label: Mudanças moderadas (novos componentes)
        - label: Mudanças significativas (refatoração de tema)
        - label: Adicionar novas classes/utilities
        - label: Modificar variáveis CSS (:root)
        - label: Media queries para responsividade

  - type: checkboxes
    id: acceptance-criteria
    attributes:
      label: Critérios de Aceitação
      description: Marque quando o agente completar estas tarefas
      options:
        - label: Mudanças visuais implementadas conforme especificação
        - label: Funcionalidade não foi quebrada pelas mudanças visuais
        - label: Responsividade testada em desktop, tablet e mobile
        - label: Acessibilidade mantida ou melhorada
        - label: Consistência com design system existente
        - label: Screenshots comparativos fornecidos (antes/depois)

  - type: markdown
    attributes:
      value: |
        ---
        ### 📝 Notas para o Agente de Codificação
        
        **Arquivos Principais:**
        - CSS: `src/main/resources/static/styles.css`
        - HTML: `src/main/resources/static/index.html`
        - JavaScript: `src/main/resources/static/app.js`
        
        **Boas Práticas UI/UX:**
        - Use as variáveis CSS existentes em `:root` para cores
        - Mantenha consistência com o design atual
        - Teste em diferentes navegadores
        - Valide contraste de cores para acessibilidade
        - Use unidades responsivas (rem, em, %, vw/vh)
        - Adicione transições suaves para mudanças visuais
        - Minimize mudanças drásticas que confundam usuários
        
        **Paleta de Cores Atual:**
        - Primary: #1a237e (azul escuro)
        - Secondary: #ff6f00 (laranja)
        - Background: #f5f5f5
        - Consulte styles.css para cores completas
        
        **Teste de Responsividade:**
        - Desktop: >1200px
        - Tablet: 768-1199px
        - Mobile: <768px
        - Use Chrome DevTools para testar diferentes dispositivos
        
        **Depois de Implementar:**
        - Tire screenshots do antes e depois
        - Teste em diferentes tamanhos de tela
        - Valide contraste em https://webaim.org/resources/contrastchecker/
